// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Hunter.DataAccess.Entities.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddOriginResoultionShortlistedFieldsInCandidateTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddOriginResoultionShortlistedFieldsInCandidateTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201508032045121_AddOriginResoultionShortlistedFieldsInCandidateTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
