// <auto-generated />
namespace Hunter.DataAccess.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removelocationfieldinvacancy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removelocationfieldinvacancy));
        
        string IMigrationMetadata.Id
        {
            get { return "201508290646591_remove-location-field-in-vacancy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
