// <auto-generated />
namespace Hunter.DataAccess.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_userprofile_field_to_activity_entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_userprofile_field_to_activity_entity));
        
        string IMigrationMetadata.Id
        {
            get { return "201508201751269_added_userprofile_field_to_activity_entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
