// <auto-generated />
namespace Hunter.DataAccess.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class candidate_resume_scheme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(candidate_resume_scheme));
        
        string IMigrationMetadata.Id
        {
            get { return "201508190916315_candidate_resume_scheme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
